#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : django-appconf
Version  : 1.0.1
Release  : 16
URL      : https://pypi.python.org/packages/source/d/django-appconf/django-appconf-1.0.1.tar.gz
Source0  : https://pypi.python.org/packages/source/d/django-appconf/django-appconf-1.0.1.tar.gz
Summary  : A helper class for handling configuration defaults of packaged apps gracefully.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: django-appconf-python
BuildRequires : django-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
django-appconf
==============
.. image:: https://secure.travis-ci.org/jezdez/django-appconf.png?branch=develop
:alt: Build Status
:target: http://travis-ci.org/jezdez/django-appconf

%package python
Summary: python components for the django-appconf package.
Group: Default

%description python
python components for the django-appconf package.


%prep
%setup -q -n django-appconf-1.0.1

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
#py.test-2.7 --verbose; py.test-3.4 --verbose;
%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}
python3 setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
